# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 03:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retrospective', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planning',
            options={'verbose_name': 'Planificaci\xf3n', 'verbose_name_plural': 'Planificaciones'},
        ),
        migrations.AlterModelOptions(
            name='retrospective',
            options={'verbose_name': 'Retrospectiva'},
        ),
        migrations.AlterModelOptions(
            name='retrospectiveuser',
            options={'verbose_name_plural': 'Retrospectivas por usuario'},
        ),
        migrations.AlterUniqueTogether(
            name='retrospectiveuser',
            unique_together=set([('retrospective', 'user')]),
        ),
    ]
