# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-31 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retrospective', '0003_auto_20170125_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprint',
            options={},
        ),
    ]
