DBNAME = ''
DBUSER = ''
DBPASSWORD = ''
DBHOST = ''
DBPORT = ''

DJ_SECRET_KEY = ''
DJ_DEBUG = True
DJ_ALLOWED_HOSTS = []

DJ_EMAIL_HOST = ''
DJ_EMAIL_PORT = ''
DJ_EMAIL_HOST_USER = ''
DJ_EMAIL_HOST_PASSWORD = ''
